// Package facade generates the curated public API of an extracted module.
//
// A generated module holds relocated upstream packages under an internal
// prefix, which makes every one of them unimportable from outside the module.
// That is deliberate: the upstream package surface is enormous, it changes
// whenever upstream changes, and almost none of it is what a consumer came for.
// The facade is the small, deliberately chosen surface that is published in its
// place, and it is the only thing a consumer may depend on.
//
// The facade is generated rather than written by hand because a hand written
// forwarding layer drifts. Upstream renames a field, changes a signature, or
// deletes a constructor, and a hand written wrapper either stops compiling in a
// place that does not explain itself or, worse, keeps compiling while meaning
// something new. Generating the surface from the loaded type information of the
// module that will actually be published makes the drift a build failure of the
// engine, before anything is tagged.
//
// Four rules decide what the generated file may contain, and each exists to
// preserve an identity a consumer can rely on:
//
//   - Types and interfaces become aliases. An alias is the same type, so a
//     consumer's implementation of a copied interface satisfies the copied
//     contract, and a value produced by the internal code is the value the
//     facade names. A redeclared struct would be a different type that merely
//     looks similar, and no amount of conversion helpers would make the two
//     interchangeable.
//   - Functions become real forwarding declarations with the resolved
//     signature. A function value assigned to a package level variable would
//     let any consumer reassign the published API at run time, so a var is
//     never generated.
//   - Constants are forwarded directly, because a constant has no identity to
//     lose.
//   - Exported variables are refused. A published mutable variable is shared
//     global state between every consumer of the module, and no facade can make
//     that safe.
//
// The generator then proves two things that a compiler alone would not. It
// walks the exported surface recursively and refuses any reachable named type
// that lives inside the generated module but has no facade alias, because such
// a type is spelled in the public API while being unnameable by a consumer.
// External module types are left exactly as they are: they keep their upstream
// package identity, so a value the facade returns is the same type the rest of
// the ecosystem passes around. It also proves, at generation time, the
// interface assertions it emits, so a failure names the interface and the
// method that is missing rather than surfacing as a compile error in a
// generated file nobody wrote.
//
// Everything the package produces is deterministic. Imports are aliased and
// ordered by rule, the API manifest is sorted and spelled with full package
// paths, and the output goes through go/format, so two runs over one commit
// produce identical bytes and a manifest comparison across a change is a real
// signal rather than noise.
package facade

import (
	"errors"
	"fmt"
	"go/token"
	"path"
	"slices"
	"strings"
)

// GeneratedHeader is the marker every file this package writes carries.
//
// It matches the convention at https://go.dev/s/generatedcode, so every Go tool
// that skips generated files skips these, and a reviewer reading the published
// module can tell the curated surface from code a human maintains.
const GeneratedHeader = "// Code generated by soapbox. DO NOT EDIT."

// Facade sentinels. Callers use errors.Is to distinguish the failure.
var (
	// ErrSpec reports an export specification that does not describe a
	// generatable facade.
	ErrSpec = errors.New("facade specification is not usable")
	// ErrMissingSymbol reports a requested symbol the loaded module does not
	// export. It is the shape an upstream removal takes.
	ErrMissingSymbol = errors.New("requested symbol is not exported by the loaded package")
	// ErrKindMismatch reports a symbol whose kind is not the kind the profile
	// declared, which is how an upstream change from an interface to a struct,
	// or from a constant to a variable, is caught before it is published.
	ErrKindMismatch = errors.New("symbol is not of the declared kind")
	// ErrMutableVar reports an exported package level variable. A published
	// variable is global mutable state shared by every consumer of the module.
	ErrMutableVar = errors.New("exported variables may not be part of the public API")
	// ErrGeneric reports a generic declaration the generator will not forward.
	ErrGeneric = errors.New("generic declaration cannot be forwarded")
	// ErrCollision reports two exports that would occupy one name in the
	// generated package.
	ErrCollision = errors.New("two exports collide on one facade name")
	// ErrLeak reports an internal named type that is reachable from the public
	// API but has no facade alias, so a consumer could receive a value of a type
	// it cannot name.
	ErrLeak = errors.New("internal type is reachable from the public API without a facade alias")
	// ErrUnrepresentable reports a type the generated package cannot spell
	// identically, such as an unnamed struct or interface carrying an
	// unexported member of another package. Writing the same characters in the
	// generated package would declare a different type, so there is no
	// spelling to publish.
	ErrUnrepresentable = errors.New("type cannot be spelled in the generated package")
	// ErrManifestChanged reports a published API that differs from the baseline
	// it was compared against.
	ErrManifestChanged = errors.New("published API differs from the baseline")
	// ErrAssertion reports a generated interface assertion that does not hold.
	ErrAssertion = errors.New("interface assertion does not hold")
	// ErrLoad reports a module the Go type checker could not load.
	ErrLoad = errors.New("generated module did not load")
)

// Kind is the declaration a facade entry produces.
//
// The profile states the kind and the generator checks it against what the
// loaded module actually holds. Restating something the type checker already
// knows is the point: a symbol that changed kind upstream is a breaking change
// to the published API, and it has to stop the run rather than quietly generate
// a different declaration than the one that was reviewed.
type Kind uint8

const (
	// KindType is a named type exposed through an alias.
	KindType Kind = iota
	// KindInterface is a named interface type exposed through an alias. It is
	// distinct from KindType only so that an upstream interface that becomes a
	// struct is reported rather than aliased.
	KindInterface
	// KindFunc is a function exposed through a forwarding declaration.
	KindFunc
	// KindConst is a constant forwarded directly.
	KindConst
	// KindVar is an exported variable. It is named so a profile that asks for
	// one is refused with an explanation rather than an unknown kind error.
	KindVar
)

// String renders the kind as the profile spells it.
func (k Kind) String() string {
	switch k {
	case KindType:
		return "type"
	case KindInterface:
		return "interface"
	case KindFunc:
		return "func"
	case KindConst:
		return "const"
	case KindVar:
		return "var"
	default:
		return "unknown"
	}
}

// ParseKind maps the profile spelling onto a Kind.
//
// It exists so the configuration layer can convert without this package
// importing configuration, which would tie the generator to one profile schema.
func ParseKind(name string) (Kind, error) {
	for _, kind := range []Kind{KindType, KindInterface, KindFunc, KindConst, KindVar} {
		if kind.String() == name {
			return kind, nil
		}
	}
	return 0, fmt.Errorf("%w: kind %q is not one of type, interface, func, const, or var", ErrSpec, name)
}

// Export is one entry of the published surface.
type Export struct {
	// Name is the identifier the generated package declares. It is always
	// explicit, because two upstream packages may export the same name and the
	// facade has one namespace: the four RBAC lister adapters collide with the
	// validation interfaces they adapt, and only an explicit name says which of
	// the two a consumer is being handed.
	Name string
	// Kind is the declaration to generate.
	Kind Kind
	// Source is the upstream qualified symbol, such as
	// k8s.io/kubernetes/pkg/registry/rbac/validation.RoleGetter. It is spelled
	// against the upstream import path rather than the relocated one because
	// that is what a profile author reads in the upstream repository, and
	// because the relocated path is derived from it by a rule this package
	// applies rather than by a second thing to keep in sync.
	Source string
	// Direct marks a generated module-local declaration. It is never accepted
	// from a user profile; an engine compatibility phase derives it.
	Direct bool
	// Doc is an optional documentation sentence for the generated declaration.
	// It is rendered above the declaration, after the provenance line the
	// generator always writes.
	Doc string
}

// Assertion is a compile time proof that a facade type implements an interface.
//
// The interface is named by its real upstream path, and the assertion is
// checked here as well as emitted, because the failure the engine can explain
// is far more useful than the one the Go compiler would report from a generated
// file: this package can say which interface, which method, and whether the
// method set was missing it entirely or had it with a different signature.
type Assertion struct {
	// Type is the facade name of the asserted type. It must be an exported
	// entry of the same specification.
	Type string
	// Pointer asserts on the pointer to the type rather than the value, which
	// is what a type with pointer receiver methods requires.
	Pointer bool
	// Interface is the qualified interface, such as
	// k8s.io/apiserver/pkg/authorization/authorizer.Authorizer. It is an
	// external module path used verbatim: an assertion against a copy of the
	// interface would prove nothing about the real one in external mode.
	Interface string
	// Local permits a compatibility-mode assertion against an engine-generated
	// module-local interface. User-authored assertions never set it.
	Local bool
}

// Spec is the config derived description of the facade to generate.
//
// The type is owned by this package rather than imported from configuration so
// the generator depends on the shape of the problem instead of on the shape of
// one profile schema, and so a test can state a surface in a few lines without
// building a whole profile.
type Spec struct {
	// ModulePath is the generated module's path, such as
	// monis.app/kk/rbac_authorizer.
	ModulePath string
	// SourcePrefix is the upstream module path every Source is spelled against,
	// such as k8s.io/kubernetes.
	SourcePrefix string
	// InternalPrefix is the module relative directory the upstream paths were
	// relocated below, such as internal/kk.
	InternalPrefix string
	// Package is the generated root package name, such as rbacauthorizer.
	Package string
	// File is the module relative path of the generated facade, such as
	// authorizer.go.
	File string
	// AssertionsFile is the module relative path of the generated assertions,
	// such as zz_generated_assertions.go. It is written even when no assertion
	// is specified, so the published tree never depends on whether a profile
	// happened to declare one.
	AssertionsFile string
	// Exports are the published entries. Order does not matter: the output is
	// sorted by facade name.
	Exports []Export
	// Assertions are the interface implementations to prove and emit.
	Assertions []Assertion
}

// resolvedExport is one export with its upstream reference resolved onto the
// relocated package the generated module actually holds.
type resolvedExport struct {
	// Export is the specification entry this was resolved from.
	Export
	// Package is the relocated import path, such as
	// monis.app/kk/rbac_authorizer/internal/kk/pkg/registry/rbac/validation.
	Package string
	// Symbol is the identifier exported by that package.
	Symbol string
}

// resolvedAssertion is one assertion with its interface reference split.
type resolvedAssertion struct {
	// Assertion is the specification entry this was resolved from.
	Assertion
	// Package is the external package holding the interface.
	Package string
	// Symbol is the interface's name in that package.
	Symbol string
}

// validate checks the specification on its own, before anything is loaded.
//
// Loading a module is the expensive half of generation, so everything that can
// be decided from the specification alone is decided first. A profile that
// names two exports the same, spells a symbol that is not an identifier, or
// asks for a variable is refused without a type checker having run.
func (s Spec) validate() ([]resolvedExport, []resolvedAssertion, error) {
	if err := checkImportPath(s.ModulePath, "module path"); err != nil {
		return nil, nil, err
	}
	if err := checkImportPath(s.SourcePrefix, "source prefix"); err != nil {
		return nil, nil, err
	}
	if err := checkInternalPrefix(s.InternalPrefix); err != nil {
		return nil, nil, err
	}
	if !token.IsIdentifier(s.Package) || token.IsExported(s.Package) {
		return nil, nil, fmt.Errorf("%w: package name %q must be a lower case Go identifier", ErrSpec, s.Package)
	}
	if err := checkGeneratedFile(s.File, "facade file"); err != nil {
		return nil, nil, err
	}
	if err := checkGeneratedFile(s.AssertionsFile, "assertions file"); err != nil {
		return nil, nil, err
	}
	if s.File == s.AssertionsFile {
		return nil, nil, fmt.Errorf("%w: the facade and the assertions cannot share the file %q", ErrSpec, s.File)
	}
	if len(s.Exports) == 0 {
		return nil, nil, fmt.Errorf("%w: at least one export is required", ErrSpec)
	}

	exports := make([]resolvedExport, 0, len(s.Exports))
	for _, export := range s.Exports {
		resolved, err := s.resolveExport(export)
		if err != nil {
			return nil, nil, err
		}
		exports = append(exports, resolved)
	}
	slices.SortFunc(exports, compareExports)
	if err := checkExportCollisions(exports); err != nil {
		return nil, nil, err
	}

	assertions, err := s.resolveAssertions(exports)
	if err != nil {
		return nil, nil, err
	}
	return exports, assertions, nil
}

// compareExports orders exports by the name the facade declares, which is
// unique once collisions are refused, and breaks a tie on the source so the
// collision itself is reported the same way on every run.
func compareExports(a, b resolvedExport) int {
	if order := strings.Compare(a.Name, b.Name); order != 0 {
		return order
	}
	return strings.Compare(a.Source, b.Source)
}

// resolveExport maps one specification entry onto the relocated package.
func (s Spec) resolveExport(export Export) (resolvedExport, error) {
	if !token.IsIdentifier(export.Name) || !token.IsExported(export.Name) {
		return resolvedExport{}, fmt.Errorf("%w: facade name %q must be an exported Go identifier", ErrSpec, export.Name)
	}
	if export.Kind == KindVar {
		return resolvedExport{}, fmt.Errorf("export %s (%s): %w", export.Name, export.Source, ErrMutableVar)
	}
	if export.Kind > KindVar {
		return resolvedExport{}, fmt.Errorf("%w: export %s has unknown kind %d", ErrSpec, export.Name, export.Kind)
	}
	upstream, symbol, err := splitSymbol(export.Source)
	if err != nil {
		return resolvedExport{}, fmt.Errorf("export %s: %w", export.Name, err)
	}
	relocated := upstream
	if export.Direct {
		root := path.Join(s.ModulePath, s.InternalPrefix) + "/"
		if !strings.HasPrefix(upstream, root) {
			return resolvedExport{}, fmt.Errorf("%w: direct package %q is not below generated internal root %s", ErrSpec, upstream, root)
		}
	} else {
		relocated, err = s.relocate(upstream)
		if err != nil {
			return resolvedExport{}, fmt.Errorf("export %s: %w", export.Name, err)
		}
	}
	return resolvedExport{Export: export, Package: relocated, Symbol: symbol}, nil
}

// resolveAssertions splits every assertion and binds it to the export it
// asserts about.
//
// An assertion about a name the facade does not export is refused rather than
// generated, because the emitted file would not compile and the reason would be
// a missing identifier rather than the profile mistake that caused it.
func (s Spec) resolveAssertions(exports []resolvedExport) ([]resolvedAssertion, error) {
	assertions := make([]resolvedAssertion, 0, len(s.Assertions))
	for _, assertion := range s.Assertions {
		index := slices.IndexFunc(exports, func(export resolvedExport) bool { return export.Name == assertion.Type })
		switch {
		case index < 0:
			return nil, fmt.Errorf("%w: assertion names %s, which the facade does not export", ErrSpec, assertion.Type)
		case exports[index].Kind != KindType:
			return nil, fmt.Errorf("%w: assertion names %s, which is exported as a %s rather than a type",
				ErrSpec, assertion.Type, exports[index].Kind)
		}
		pkgPath, symbol, err := splitSymbol(assertion.Interface)
		if err != nil {
			return nil, fmt.Errorf("assertion on %s: %w", assertion.Type, err)
		}
		insideModule := pkgPath == s.ModulePath || strings.HasPrefix(pkgPath, s.ModulePath+"/")
		switch {
		case insideModule && !assertion.Local:
			return nil, fmt.Errorf("%w: assertion on %s names %s, which is inside the generated module; an assertion against a copied interface proves nothing about the real one",
				ErrSpec, assertion.Type, assertion.Interface)
		case assertion.Local && !strings.HasPrefix(pkgPath, path.Join(s.ModulePath, s.InternalPrefix)+"/"):
			return nil, fmt.Errorf("%w: local assertion on %s names %s outside the generated internal root", ErrSpec, assertion.Type, assertion.Interface)
		}
		assertions = append(assertions, resolvedAssertion{Assertion: assertion, Package: pkgPath, Symbol: symbol})
	}
	slices.SortFunc(assertions, compareAssertions)
	for i := 1; i < len(assertions); i++ {
		if compareAssertions(assertions[i-1], assertions[i]) == 0 {
			return nil, fmt.Errorf("%w: assertion that %s implements %s is declared twice",
				ErrSpec, assertions[i].Type, assertions[i].Interface)
		}
	}
	return assertions, nil
}

// compareAssertions orders assertions by asserted type, then interface, then
// pointer form, which is a total order over what makes an assertion distinct.
func compareAssertions(a, b resolvedAssertion) int {
	if order := strings.Compare(a.Type, b.Type); order != 0 {
		return order
	}
	if order := strings.Compare(a.Interface, b.Interface); order != 0 {
		return order
	}
	return boolCompare(a.Pointer, b.Pointer)
}

// boolCompare orders false before true.
func boolCompare(a, b bool) int {
	switch {
	case a == b:
		return 0
	case b:
		return -1
	default:
		return 1
	}
}

// checkExportCollisions refuses two entries that would occupy one name.
//
// The exports arrive sorted, so a collision is always an adjacent pair and the
// reported pair is the same on every run. The message names both sources,
// because the fix is to give one of them an explicit facade name and knowing
// only the name would not say which two upstream symbols have to be told apart.
func checkExportCollisions(exports []resolvedExport) error {
	for i := 1; i < len(exports); i++ {
		if exports[i-1].Name != exports[i].Name {
			continue
		}
		return fmt.Errorf("%s and %s both export %s: %w",
			exports[i-1].Source, exports[i].Source, exports[i].Name, ErrCollision)
	}
	return nil
}

// relocate maps an upstream package path onto the path the generated module
// holds it at.
//
// The rule is relocation's: an upstream path is preserved whole below the
// internal prefix. Applying it here rather than taking a resolved path from the
// caller means the profile spells one path, the one a reader can look up
// upstream, and the generated module's layout follows from it.
func (s Spec) relocate(upstream string) (string, error) {
	if upstream != s.SourcePrefix && !strings.HasPrefix(upstream, s.SourcePrefix+"/") {
		return "", fmt.Errorf("%w: package %q is not below the source prefix %s", ErrSpec, upstream, s.SourcePrefix)
	}
	relative := strings.TrimPrefix(strings.TrimPrefix(upstream, s.SourcePrefix), "/")
	if relative == "" {
		return "", fmt.Errorf("%w: package %q names the source module itself", ErrSpec, upstream)
	}
	return path.Join(s.ModulePath, s.InternalPrefix, relative), nil
}

// internalTo reports whether an import path is inside the generated module.
func (s Spec) internalTo(pkgPath string) bool {
	return pkgPath == s.ModulePath || strings.HasPrefix(pkgPath, s.ModulePath+"/")
}

// unnameable reports whether a consumer of the generated module is unable to
// import a package, which is what makes a type declared there unnameable and so
// unpublishable without a facade alias.
//
// Two kinds of package qualify, and they fail the same way for the same reason.
// Everything inside the generated module is code this run relocated below an
// internal prefix, so an importer outside the module cannot reach it. And any
// package with an internal path element, in this module or in a dependency, is
// importable only from within the subtree rooted at that element's parent; a
// consumer is by definition somewhere else. A dependency that exposes one of
// its own internal types in its public API is an upstream mistake, but
// republishing that type here would make it this module's mistake: a consumer
// would receive a value whose type it cannot declare, implement, or accept as a
// parameter.
func (s Spec) unnameable(pkgPath string) bool {
	if s.internalTo(pkgPath) {
		return true
	}
	return slices.Contains(strings.Split(pkgPath, "/"), internalElement)
}

// internalElement is the path element that makes a package importable only from
// within the subtree rooted at its parent.
const internalElement = "internal"

// splitSymbol splits a qualified symbol into its package path and identifier.
//
// The separator is the last dot after the last slash, because a package path
// element may contain a dot, as every domain qualified module path does, while
// a Go identifier may not.
func splitSymbol(qualified string) (pkgPath, name string, err error) {
	slash := strings.LastIndex(qualified, "/")
	dot := strings.LastIndex(qualified[slash+1:], ".")
	if dot < 0 {
		return "", "", fmt.Errorf("%w: %q does not name a package qualified symbol", ErrSpec, qualified)
	}
	dot += slash + 1
	pkgPath, name = qualified[:dot], qualified[dot+1:]
	if err := checkImportPath(pkgPath, "package"); err != nil {
		return "", "", fmt.Errorf("%q: %w", qualified, err)
	}
	if !token.IsIdentifier(name) || !token.IsExported(name) {
		return "", "", fmt.Errorf("%w: %q does not end in an exported Go identifier", ErrSpec, qualified)
	}
	return pkgPath, name, nil
}

// checkImportPath rejects the shapes an import path may not take.
//
// The check is deliberately structural rather than a call into the module
// system: what matters here is that the path can be handed to the loader and
// compared by prefix, so a path that is empty, absolute, relative, or carries
// an empty element would make both operations mean something other than they
// appear to.
func checkImportPath(pkgPath, what string) error {
	switch {
	case pkgPath == "":
		return fmt.Errorf("%w: a %s is required", ErrSpec, what)
	case path.IsAbs(pkgPath):
		return fmt.Errorf("%w: %s %q is absolute", ErrSpec, what, pkgPath)
	case pkgPath != path.Clean(pkgPath):
		return fmt.Errorf("%w: %s %q is not a clean path", ErrSpec, what, pkgPath)
	case strings.HasPrefix(pkgPath, "."):
		return fmt.Errorf("%w: %s %q is relative", ErrSpec, what, pkgPath)
	}
	return nil
}

// checkInternalPrefix requires the destination root that makes relocated
// packages unimportable from outside the generated module.
//
// Relocation enforces this too. It is repeated because a facade generated
// against a prefix without an internal element would be aliasing types a
// consumer can already import directly, which is a published surface nobody
// designed rather than a mistake the compiler would catch.
func checkInternalPrefix(prefix string) error {
	if err := checkImportPath(prefix, "internal prefix"); err != nil {
		return err
	}
	if !slices.Contains(strings.Split(prefix, "/"), internalElement) {
		return fmt.Errorf("%w: internal prefix %q has no internal element", ErrSpec, prefix)
	}
	return nil
}

// checkGeneratedFile requires a module relative Go file at the module root.
//
// The facade is the module's root package, so a generated file in a
// subdirectory would belong to a different package than the one it declares.
func checkGeneratedFile(name, what string) error {
	switch {
	case name == "":
		return fmt.Errorf("%w: a %s is required", ErrSpec, what)
	case name != path.Base(name):
		return fmt.Errorf("%w: %s %q must be at the module root", ErrSpec, what, name)
	case !strings.HasSuffix(name, ".go"):
		return fmt.Errorf("%w: %s %q must be a Go file", ErrSpec, what, name)
	case strings.HasSuffix(name, "_test.go"):
		return fmt.Errorf("%w: %s %q must not be a test file", ErrSpec, what, name)
	}
	return nil
}
