package generate

import (
	"context"
	"fmt"

	"github.com/enj/soapbox/tools/internal/config"
	"github.com/enj/soapbox/tools/internal/facade"
)

// runFacade generates the curated public API of both scratch modules and refuses
// a prune that changed it.
//
// This is the gate the whole pre-prune pass exists to make possible. The
// argument for pruning a package is that no consumer can tell: the code that
// survives already uses the published API, so removing the internal one changes
// nothing a consumer could observe. That argument is checkable, and this is
// where it is checked, by generating the same facade from both trees and
// refusing any difference at all.
//
// The comparison is the manifest's rather than a textual diff of the generated
// files. A manifest is spelled with full package paths and sorted, so a type
// that moved between packages while keeping its name does not compare equal to
// the type it replaced, while a formatting change that no consumer can observe
// does not produce a difference nobody needs to review. Nothing beyond what the
// manifest states is compared: a parameter name is not part of a Go function's
// identity, and refusing a rename would block a change consumers cannot see.
func (r *run) runFacade(ctx context.Context) error {
	spec, err := facadeSpec(r.cfg)
	if err != nil {
		return policyError(stageFacade, err)
	}

	pre, err := r.generateFacade(ctx, r.paths.PreModule, spec, preDirName)
	if err != nil {
		return err
	}
	post, err := r.generateFacade(ctx, r.paths.PostModule, spec, postDirName)
	if err != nil {
		return err
	}

	// Diff is computed before CheckAgainst so the report carries the differences
	// in their rendered form whether or not the run continues. CheckAgainst
	// renders them into its error too, but a refusal that is only readable from
	// an error string is one CI cannot act on.
	differences := facade.Diff(pre.Manifest, post.Manifest)
	r.report.recordFacade(pre, post, differences)

	if err := post.Manifest.CheckAgainst(pre.Manifest); err != nil {
		return policyError(stageFacade, fmt.Errorf("pruning changed the published API: %w", err))
	}

	r.preFacade = pre
	r.postFacade = post
	r.facadeDiffs = renderDifferences(differences)
	return nil
}

// generateFacade renders one module's facade.
//
// The environment is the Go runner's loader environment rather than the
// process's. A facade is generated by type checking a real module, so an ambient
// environment would let a GOFLAGS value or a module cache chosen by whoever
// started the process decide what the published API is.
func (r *run) generateFacade(ctx context.Context, dir string, spec facade.Spec, name string) (facade.Result, error) {
	runner, err := r.opts.Go.WithDir(dir)
	if err != nil {
		return facade.Result{}, runtimeError(stageFacade, fmt.Errorf("%s facade: %w", name, err))
	}
	env, err := runner.LoaderEnv(ctx)
	if err != nil {
		return facade.Result{}, runtimeError(stageFacade, fmt.Errorf("%s facade: %w", name, err))
	}
	// Generating a facade type checks a real module, so a load that could not
	// run is a toolchain condition. The sentinels are the ones that describe the
	// surface the profile asked to publish.
	result, err := facade.Generate(ctx, facade.Options{Dir: dir, Env: env, Spec: spec})
	if err != nil {
		return facade.Result{}, classify(stageFacade, fmt.Errorf("%s facade: %w", name, err), facadeSemantic...)
	}
	return result, nil
}

// facadeSpec translates the profile's facade section into the generator's own
// shape.
//
// Exports and aliases are one list here. They differ in the profile only by
// intent: an export republishes an upstream symbol under its own name, and an
// alias republishes one under a different name because two upstream packages
// export the same name and the facade has a single namespace. The generator
// spells both as an explicit name against an upstream source, so the distinction
// has already done its work by the time it reaches this point.
func facadeSpec(cfg *config.Config) (facade.Spec, error) {
	spec := facade.Spec{
		ModulePath:     cfg.Destination.Module,
		SourcePrefix:   cfg.Source.ImportPrefix,
		InternalPrefix: cfg.Destination.InternalPrefix,
		Package:        cfg.Facade.Package,
		File:           cfg.Facade.File,
		AssertionsFile: cfg.Facade.AssertionsFile,
	}
	entries := make([]config.Export, 0, len(cfg.Facade.Exports)+len(cfg.Facade.Aliases))
	entries = append(entries, cfg.Facade.Exports...)
	for _, alias := range cfg.Facade.Aliases {
		entries = append(entries, config.Export{Name: alias.Name, Kind: alias.Kind, Source: alias.Source})
	}
	for _, entry := range entries {
		kind, err := facade.ParseKind(entry.Kind)
		if err != nil {
			return facade.Spec{}, fmt.Errorf("facade entry %s: %w", entry.Name, err)
		}
		spec.Exports = append(spec.Exports, facade.Export{Name: entry.Name, Kind: kind, Source: entry.Source, Direct: entry.Direct})
	}
	for _, assertion := range cfg.Facade.InterfaceAssertions {
		spec.Assertions = append(spec.Assertions, facade.Assertion{
			Type:      assertion.Type,
			Pointer:   assertion.Pointer,
			Interface: assertion.Interface,
			Local:     assertion.Local,
		})
	}
	return spec, nil
}

// renderDifferences renders manifest differences for the type policy, which
// consumes them as opaque strings.
func renderDifferences(differences []facade.Difference) []string {
	rendered := make([]string, len(differences))
	for i, difference := range differences {
		rendered[i] = difference.String()
	}
	return rendered
}
