package config_test

import (
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/config"
)

// TestProfileBytesExcludesOperationalFields proves that changing a field that
// cannot change a generated byte leaves the replay profile identity alone. A new
// epoch is expensive, so this list is a contract rather than an accident.
func TestProfileBytesExcludesOperationalFields(t *testing.T) {
	tests := []struct {
		name      string
		mutations []mutation
	}{
		{
			name:      "chunk size",
			mutations: []mutation{{old: "chunkSize: 200", new: "chunkSize: 25"}},
		},
		{
			name:      "publication mode",
			mutations: []mutation{{old: "mode: manual", new: "mode: automatic"}},
		},
		{
			name: "vanity location",
			mutations: []mutation{
				{old: "  repository: enj/enj.github.io", new: "  repository: enj/pages"},
				{old: "path: kk/rbac_authorizer/index.html", new: "path: modules/rbac_authorizer/index.html"},
			},
		},
		{
			name:      "state ref",
			mutations: []mutation{{old: "stateRef: refs/heads/soapbox-state", new: "stateRef: refs/heads/soapbox-cursor"}},
		},
		{
			name:      "progress ref namespace",
			mutations: []mutation{{old: "progressRefPrefix: refs/soapbox/progress/", new: "progressRefPrefix: refs/soapbox/chunks/"}},
		},
		{
			name:      "consumer branch",
			mutations: []mutation{{old: "  branch: main", new: "  branch: release"}},
		},
		{
			name: "destination repository and remote",
			mutations: []mutation{
				{old: "  repository: enj/rbac_authorizer\n  remote: https://github.com/enj/rbac_authorizer.git", new: "  repository: enj/rbac\n  remote: https://github.com/enj/rbac.git"},
				{old: "repositoryURL: https://github.com/enj/rbac_authorizer", new: "repositoryURL: https://github.com/enj/rbac"},
			},
		},
		{
			name:      "observational closure limit",
			mutations: []mutation{{old: "maxNonTestLines: 5000", new: "maxNonTestLines: 9000"}},
		},
		{
			name:      "closure golden",
			mutations: []mutation{{old: "golden: testdata/closure/rbac-v1.36.1.json", new: "golden: testdata/closure/other.json"}},
		},
		{
			name:      "tracked branches",
			mutations: []mutation{{old: "      - master\n", new: "      - master\n      - release-1.36\n"}},
		},
		{
			name:      "prerelease selection",
			mutations: []mutation{{old: "includePrereleases: true", new: "includePrereleases: false"}},
		},
	}

	baseline := profileBytes(t, baseProfile)
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			mutated := mutate(t, baseProfile, test.mutations)
			if mutated == baseProfile {
				t.Fatal("the mutation did not change the profile")
			}
			// The change must be real: canonical bytes differ even though the
			// replay identity does not.
			if canonicalOf(t, mutated) == canonicalOf(t, baseProfile) {
				t.Fatal("the mutation did not change the canonical profile")
			}
			if got := profileBytes(t, mutated); got != baseline {
				t.Fatalf("operational change altered the replay profile identity:\n%s", diffFirstLine(baseline, got))
			}
		})
	}
}

// TestProfileBytesIncludesOutputAffectingFields is the control: everything that
// changes generated bytes must change the replay profile identity.
func TestProfileBytesIncludesOutputAffectingFields(t *testing.T) {
	tests := []struct {
		name      string
		mutations []mutation
	}{
		{name: "toolchain", mutations: []mutation{{old: "toolchain: go1.26.5", new: "toolchain: go1.26.4"}}},
		{name: "module path", mutations: []mutation{{old: "  module: monis.app/kk/rbac_authorizer", new: "  module: monis.app/kk/rbac"}, {old: "importPath: monis.app/kk/rbac_authorizer", new: "importPath: monis.app/kk/rbac"}, {old: "probeURL: https://monis.app/kk/rbac_authorizer?go-get=1", new: "probeURL: https://monis.app/kk/rbac?go-get=1"}}},
		{name: "internal prefix", mutations: []mutation{{old: "internalPrefix: internal/kk", new: "internalPrefix: internal/upstream"}}},
		{name: "root package", mutations: []mutation{{old: "rootPackage: rbacauthorizer", new: "rootPackage: rbacauth"}, {old: "facade:\n  package: rbacauthorizer", new: "facade:\n  package: rbacauth"}}},
		{name: "package roots", mutations: []mutation{{old: "    - plugin/pkg/auth/authorizer/rbac\n", new: "    - plugin/pkg/auth/authorizer/rbac\n    - pkg/registry/rbac/validation\n"}}},
		{name: "prune entries", mutations: []mutation{{old: "  files:\n    - pkg/apis/rbac/v1/register.go\n", new: "  files:\n    - pkg/apis/rbac/v1/register.go\n    - pkg/apis/rbac/v1/defaults.go\n"}}},
		{name: "required entries", mutations: []mutation{{old: "  required:\n    - pkg/apis/rbac/v1/doc.go\n", new: "  required:\n    - pkg/apis/rbac/v1/doc.go\n    - pkg/apis/rbac/v1/evaluation_helpers.go\n"}}},
		{name: "denied imports", mutations: []mutation{{old: "    - k8s.io/kubernetes/pkg/apis/rbac\ncl", new: "    - k8s.io/kubernetes/pkg/apis/rbac\n    - k8s.io/kubernetes/pkg/features\ncl"}}},
		{name: "test inclusion", mutations: []mutation{{old: "includeTests: false", new: "includeTests: true"}}},
		{name: "dependency cost gates", mutations: []mutation{{old: "maxCopiedLines: 0", new: "maxCopiedLines: 500"}, {old: "maxModuleZipBytes: 0", new: "maxModuleZipBytes: 1048576"}}},
		{name: "dependency cadence and leverage gates", mutations: []mutation{{old: "maxReleasesPerMinor: 0", new: "maxReleasesPerMinor: 6"}, {old: "minModulesRemoved: 0", new: "minModulesRemoved: 1"}, {old: "minPackagesRemoved: 0", new: "minPackagesRemoved: 4"}, {old: "minLinesRemoved: 0", new: "minLinesRemoved: 900"}}},
		{name: "type policy", mutations: []mutation{{old: "  policy: prefer-external\n  pairs:\n    - internal: k8s.io/kubernetes/pkg/apis/rbac\n      external: k8s.io/api/rbac/v1", new: "  policy: keep-internal\n  pairs: []"}}},
		{name: "facade exports", mutations: []mutation{{old: "  aliases:\n", new: "    - name: RulesAllow\n      kind: func\n      source: k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RulesAllow\n  aliases:\n"}}},
		{name: "commit committer", mutations: []mutation{{old: "    name: soapbox[bot]", new: "    name: soapbox-publisher[bot]"}}},
		{name: "commit trailer key", mutations: []mutation{{old: "trailerKey: Kubernetes-commit", new: "trailerKey: Upstream-commit"}}},
		{name: "release mapping", mutations: []mutation{{old: "minimumRelease: v1.36.1", new: "minimumRelease: v1.36.2"}, {old: "firstTag: v0.36.1", new: "firstTag: v0.36.2"}}},
		{name: "source import prefix", mutations: []mutation{{old: "importPrefix: k8s.io/kubernetes", new: "importPrefix: k8s.io/kubernetes2"}, {old: "    - k8s.io/kubernetes/pkg/apis/rbac\ncl", new: "    - k8s.io/kubernetes2/pkg/apis/rbac\ncl"}, {old: "internal: k8s.io/kubernetes/pkg/apis/rbac", new: "internal: k8s.io/kubernetes2/pkg/apis/rbac"}, {old: "source: k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.New", new: "source: k8s.io/kubernetes2/plugin/pkg/auth/authorizer/rbac.New"}, {old: "source: k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RBACAuthorizer", new: "source: k8s.io/kubernetes2/plugin/pkg/auth/authorizer/rbac.RBACAuthorizer"}, {old: "source: k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleGetter", new: "source: k8s.io/kubernetes2/plugin/pkg/auth/authorizer/rbac.RoleGetter"}}},
		{name: "anchor commit", mutations: []mutation{{old: `anchorCommit: ""`, new: `anchorCommit: "1f0c2b3a4d5e6f708192a3b4c5d6e7f809a1b2c3"`}}},
		// The three prose values are rendered verbatim into the committed
		// NOTICE, README, and root doc comment, so each one changes generated
		// bytes exactly as renaming a package would.
		{name: "upstream project name", mutations: []mutation{{old: "  project: Kubernetes\n", new: "  project: Kubernetes Core\n"}}},
		{name: "upstream licence identifier", mutations: []mutation{{old: "  license: Apache-2.0\n", new: "  license: MIT\n"}}},
		{name: "destination summary", mutations: []mutation{{old: " consumable Go module.\n", new: " consumable Go library.\n"}}},
		{name: "compatibility apiserver", mutations: []mutation{{old: "apiserver: external", new: "apiserver: local"}}},
		{name: "forbidden modules", mutations: []mutation{{old: "forbiddenModules: []", new: "forbiddenModules:\n    - k8s.io/legacy-cloud-providers"}}},
	}

	baseline := profileBytes(t, baseProfile)
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			mutated := mutate(t, baseProfile, test.mutations)
			if got := profileBytes(t, mutated); got == baseline {
				t.Fatal("an output affecting change left the replay profile identity unchanged")
			}
		})
	}
}

// TestProfileBytesIncludesDependencyOverrides pins the policy control that can
// change whether a proposed staging copy enters the generated tree. Overrides
// are validated against copy-approved profiles, but ProfileBytes also accepts a
// constructed Config, so this isolates the override from every other policy
// field and proves it participates in the epoch identity itself.
func TestProfileBytesIncludesDependencyOverrides(t *testing.T) {
	cfg, err := config.Decode([]byte(baseProfile))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	baseline, err := cfg.ProfileBytes()
	if err != nil {
		t.Fatalf("profile bytes: %v", err)
	}

	cfg.Dependencies.Overrides = []config.DependencyOverride{{
		Package:       "staging/src/k8s.io/api/example",
		Gate:          "maxCopiedLines",
		Justification: "temporary measured exception",
		Approver:      "release engineering",
		ExpiresAfter:  "v1.36",
	}}
	changed, err := cfg.ProfileBytes()
	if err != nil {
		t.Fatalf("profile bytes with override: %v", err)
	}
	if string(changed) == string(baseline) {
		t.Fatal("a dependency override left the replay profile identity unchanged")
	}
}

// TestProfileBytesIsStableAcrossCalls guards against aliasing between the view
// and the configuration it is built from.
func TestProfileBytesIsStableAcrossCalls(t *testing.T) {
	cfg, err := config.Decode([]byte(baseProfile))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	first, err := cfg.ProfileBytes()
	if err != nil {
		t.Fatalf("profile bytes: %v", err)
	}
	canonical, err := cfg.Canonical()
	if err != nil {
		t.Fatalf("canonical: %v", err)
	}
	second, err := cfg.ProfileBytes()
	if err != nil {
		t.Fatalf("profile bytes: %v", err)
	}
	if string(first) != string(second) {
		t.Fatal("ProfileBytes is not stable across calls")
	}
	if len(canonical) == 0 {
		t.Fatal("canonical bytes are empty")
	}
}

// profileBytes renders the replay profile identity of a profile.
func profileBytes(t *testing.T, profile string) string {
	t.Helper()
	cfg, err := config.Decode([]byte(profile))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	bytes, err := cfg.ProfileBytes()
	if err != nil {
		t.Fatalf("profile bytes: %v", err)
	}
	return string(bytes)
}

// diffFirstLine reports the first differing line of two renderings.
func diffFirstLine(want, got string) string {
	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")
	for i := range max(len(wantLines), len(gotLines)) {
		var w, g string
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if w != g {
			return "want " + w + "\ngot  " + g
		}
	}
	return "no line differs"
}
